### PR TITLE
use extracted Joi validationscheme

### PR DESCRIPTION
**Pull request by nyrosmith**
I extracted the Joi scheme into its own package and adjusted webpack-validator to use it.
I had to use the --no-verify flag bc there are no test left atm.
I think it is important to get this PR merged fast because otherwise I always have to merge with the new webpck-config-validationscheme package.
@jonathanewerner I really don't know how to fix tests & coverage as there is not much left right now.
Help would be highly appreciated so we can move on.

PS: As soon as this gets merged I'd move all scheme related issues to the scheme repo.

### CODE REVIEW

**Comment by jonathanewerner** [comment]
Hi there. I've been thinking about that monorepo again. Working with multiple repos is a nightmare for integration tests. I also expect validation needs beyond joi, which would have to be extracted into yet another repo. The schema and this other stuff would have to be required by yet another package called webpack-validator-core then, which in turn would be used from webpack-validator and webpack-validator-cli. 
So we are talking about
- webpack-validator
- webpack-validator-cli
- webpack-validator-core
- webpack-validator-joi-schema
- webpack-validator-...

This is not feasible. I think going the Babel repo structure would be nice - maybe also using lerna. I've got quite some time tomorrow. :)

**Comment by bebraw** [comment]
Monorepo would work for me.

Option - push it all below **webpack-validator** org. Then you get `cli`, `core` etc. below that, but this won't help with your integration test problem. Just a little more organized this way. Monorepo would give a similar benefit.

**Comment by nyrosmith** [comment]
I don't like the monorepo approach, but this is just an personal opinion. If most of you prefer the monorepo approach pls go for it.

**Comment by nyrosmith** [comment]
But webpack-config-validationscheme is already published on npm. How do we handle this?

**Comment by jonathanewerner** [comment]
@nyrosmith you do realize that monorepo still allows multiple npm packages, right? so `webpack-config-validationscheme` already being released does not interfere with putting it in a monorepo. The only big downside is not being able to use semantic-release, which is quite a bummer. 
Don't really get the "making it harder to dive into the code" aspect, i'd argue for the opposite. Dependent code can be found in the same repo, which makes understanding interdependencies way easier, especially because many editors/tools take a git repo as the root of a "project", which makes this even harder.

**Comment by nyrosmith** [comment]
Ok, lets make it so.... @jonathanewerner can you do the setup for the repo?

**Comment by kentcdodds** [comment]
I personally feel like doing this is overcomplicating things. But I haven't been a very active contributor lately, so feel free to ignore me. But honestly I think we could have two repos:

1. The actual validator which exposes a node API to the raw schema as well as running a config through it. It can even log errors as it's doing today.
2. The cli which utilizes the node API's raw schema to run a given config through and log errors (and fail a build potentially).

It seems pretty simple to me. But maybe my vision is smaller than yours ¯\\\_(ツ)_/¯

**Comment by nyrosmith** [comment]
@kentcdodds I have a fantastic vision and the name webpack-validator won't fit :)

**Comment by jonathanewerner** [comment]
Hey guys, i wen't down the monorepo road, partly because i just wanna try the babel setup, partly because i wanna make modularization easier. see [here](https://github.com/js-dxtools/webpack-validator/pull/64). let's see where this leads. :)

**Pull request closed without merging**
