### PR TITLE
feat(webpack-dev-server): Validate webpack-dev-server specific fields

### LINKED ISSUE #21: Validate webpack-dev-server specific fields
See https://webpack.github.io/docs/webpack-dev-server.html .

### PR DESCRIPTION
**Pull request by nlarche**
according to the source :
https://github.com/webpack/webpack-dev-server/blob/master/bin/webpack-dev-server.js

closes #21

### CODE REVIEW

**Comment by bebraw** [comment]
Looks good to me. Maybe some of those `Joi.object` bits could use more definition.

**Comment by jonathanewerner** [comment]
Great work, especially kudos for adapting the existing code patterns so nicely. 👍🏻 
@bebraw's point is surely valid, but not necessarily a prerequisite for merging this PR, it can be fleshed out later. What do you think, @nlarche? Would it make sense to add some more stuff here or is it enough like this? I'm also wondering if it would make sense to make some properties `.required()`?

**Comment by nlarche** [comment]
@bebraw, @jonathanewerner, I think those `joi.object` could be defined in an another PR.
@jonathanewerner, i'm not sure to make some properties `.required()` would make sens, you can use some properties inline with the npm script. Unless we want to force the use of `devServer` properties

**Comment by bebraw** [comment]
@nlarche Another PR would work, yeah.

**Comment by jonathanewerner** [comment]
Naa, forcing them when it's also possible to specify them via cli would be weird. K, let's merge this and iterate on it later on. :+1:

**Pull request merged**
