### PR TITLE
fix: Set default empty object for validate options

### PR DESCRIPTION
**Pull request by newtmitch**
Default option object to keep caller from having to pass empty object during function invocation when using CJS-based library import.

functionality impacts: none known

### CODE REVIEW

**Comment by newtmitch** [comment]
Sorry, I forgot to create an issue for this before submitting the fix. I can supply a webpack config that doesn't work against 2.2.4, 2.2.5, and master branches. It works fine on 2.2.3. I'm using `const validator = require('webpack-validator')` instead of `import` which is why I think your tests weren't picking up the issue.

**Comment by kentcdodds** [comment]
Cool, thanks for the PR! This looks good to me. I'd like @bebraw and/or @jonathanewerner to review this as well.

**Comment by newtmitch** [comment]
Sure thing - glad to help!

**Comment by kentcdodds** [comment]
Looks like this will fix #122

**Comment by kentcdodds** [comment]
I'll go ahead and merge this. Apologies for breaking people.

**Pull request merged**
